subprojects {
    apply plugin: 'java'

    group = rootProject.property('maven_group')
    version = rootProject.property('mod_version')

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
        it.options.encoding = 'UTF-8'
    }
}
