org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod
mod_version=1.3.0-mc26.2-release
mod_id=packping
maven_group=com.stromblex

# Minecraft
minecraft_version=26.2
minecraft_version_max=26.2
mc_label=26.2

# Fabric
fabric_loom_version=1.16.3
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2
fabric.loom.disableObfuscation=true

# NeoForge
neoforge_version=26.2.0.3-beta
moddev_version=2.0.141
